### ISSUE TITLE
Feature request: Vray RENDERERS

### ISSUE THREAD

**Issue by mmasdoria** [aws-deadline/deadline-cloud-for-3ds-max#33]
### Use Case

I want to use vray renderer in 3dsma but it seems not allowed yet in deadline-cloud-for-3ds-max.
I can see in data_const.py : 
 ALLOWED_RENDERERS = ["Default_Scanline_Renderer", "ART_Renderer"]

### Proposed Solution

Do you know when Vray renderer will be available ?

**Comment by ddneilson** [comment]
Thank you for the interest in our product, and taking the time to open a feature request. We'll add this to our list of issues to prioritize, but we cannot provide an estimate for when this work might be taken up by our team. In the meantime, we'd be happy to accept a pull request from the community that adds this functionality.

**Comment by maxschramp** [comment]
I was able to add Corona do my data_const.py file but I've yet to successfully render with it as I am still setting up my AWS farm. I may have some free time in the next week or two to delve deeper into it and put together a PR.

**Comment by maxschramp** [comment]
I've been thinking about this for a couple weeks, when I get the current renderer using `rt.renderers.current` in 3dsMax Python it shows up as `V_Ray_6__update_2_1`. I'm assuming that other V-Ray versions will show up in a similar format with the version formatting at the end, I'm going to see if there's a good way to do this without adding multiple V-Ray versions to the dictionary but wanted to update the thread with this context.

**Comment by maxschramp** [comment]
@mmasdoria merged!

**Comment by jairaws** [comment]
Support for V-Ray renders released in v0.1.2.
https://github.com/aws-deadline/deadline-cloud-for-3ds-max/pull/64
