### ISSUE TITLE
Bug: Adaptor Occasionally hangs due to dialog messages

### ISSUE THREAD

**Issue by yuanmich2** [aws-deadline/deadline-cloud-for-3ds-max#49]
### Expected Behaviour

The adaptor needs to be able to recover or at least throw errors when problems arise.

### Current Behaviour

The adaptor freezes and does not print why.

### Reproduction Steps

I do not know how to to force an error to pop up, but I'll explain what happened on my machine.

I had a CMF worker that was running fine, but it started freezing on the "Launching 3ds Max" step which was a problem I had thought I figured out the solution to here: https://github.com/aws-deadline/deadline-cloud-for-3ds-max/issues/39

I opened up a new cmd prompt as my deadline worker user like this:
```
runas /profile /user:deadline-worker cmd
```
And then executed the last command I saw in the logs which was this:
```
3dsmax -U PythonHost "C:\Program Files\Python310\lib\site-packages\deadline\max_adaptor\MaxClient\max_client.py"
```

I was then met with this popup:
![81605fc3a3434a7844ceb5b3626e8ed4](https://github.com/user-attachments/assets/36d3dd63-3dce-47c0-8238-c9b371690b2a)

I chose to "Continue without restore" and suddenly the renders started working again.

### Code Snippet

There are a number of CLI flags that the adaptor is not using which may have been able to resolve these kinds of issues. 3ds Max CLI docs: https://help.autodesk.com/view/3DSMAX/2023/ENU/?guid=GUID-1A97CFEC-60A3-4221-B9C3-5C808E2AED35

The most relevant flags are probably `-silent` and `-dm`.

The description for `-silent` is "Starts the program without the splash screen and any dialogs that might block script execution."

The `-dm` flag is described in more detail here: https://help.autodesk.com/view/3DSMAX/2024/ENU/?guid=GUID-48A78515-C24B-4E46-AC5F-884FBCF40D59
> Dialog Monitor state. When on, the dialog monitor watches for dialogs from plug-ins, and closes them. Valid choices are: 'on|off', 'yes|no', '1|0' and 'true|false'.

**Comment by sakshie95** [comment]
Thank you @yuanmich2 for filing a bug. We appreciate the time take by the community supporting the product.

The reproduction steps and code snippet are really helpful. While we try to reproduce the issue on our end, could you confirm if supplying the ``silent`` and ``-dm`` flags in the 3dsmax cli command fixed the issue for you i.e were you able to continue to render without running into the failure dialog automatically?

**Comment by yuanmich2** [comment]
As luck would have it, I ran into the startup failure detection error earlier today and instead of clicking "Continue Without Restore" I ran the command with -silent and it worked.

**Comment by jairaws** [comment]
Fixed by this [PR](https://github.com/aws-deadline/deadline-cloud-for-3ds-max/pull/52).
