### ISSUE TITLE
Bug: hatch run test Error

### ISSUE THREAD

**Issue by kadazusa** [aws-deadline/deadline-cloud-for-3ds-max#55]
### Expected Behaviour

In the Development workflow, after building deadline-cloud-for-3ds-max, the hatch run test process completes successfully.

### Current Behaviour

When running hatch run test, the following error occurs:
```
Installing collected packages: py-partiql-parser, nh3, zipp, xmltodict, urllib3, typing-extensions, types-pyyaml, tomli, six, ruff, rfc3986, PyYAML, pywin32-ctypes, Pygments, pycparser, pluggy, platformdirs, pkginfo, pathspec, packaging, mypy-extensions, more-itertools, mdurl, MarkupSafe, jmespath, iniconfig, idna, execnet, exceptiongroup, docutils, coverage, colorama, charset-normalizer, certifi, backports.tarfile, werkzeug, requests, readme-renderer, python-dateutil, pytest, mypy, markdown-it-py, Jinja2, jaraco.functools, jaraco.context, jaraco.classes, importlib-metadata, click, cffi, rich, responses, requests-toolbelt, pytest-xdist, pytest-cov, keyring, cryptography, botocore, black, twine, s3transfer, boto3, moto
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\<username>\\AppData\\Local\\hatch\\env\\virtual\\deadline-cloud-for-3ds-max\\b6hzQtbt\\deadline-cloud-for-3ds-max\\Lib\\site-packages\\moto\\stepfunctions\\parser\\asl\\component\\state\\exec\\state_map\\item_reader\\eval\\resource_output_transformer\\transformer_csv.py'
Failed with exit code: 1
```
However, the actual file path is:
```
C:\Users\<username>\AppData\Local\hatch\env\virtual\deadline-cloud-for-3ds-max\b6hzQtbt\deadline-cloud-for-3ds-max\Lib\site-packages\moto\stepfunctions\parser\asl\component\state\exec\state_map\item_reader\eval\resource_output_transformer\transformer.py
```

### Reproduction Steps

After building the deadline-cloud-for-3ds-max package with hatch build, running hatch run test.

### Code Snippet

n/a

**Comment by jairaws** [comment]
Thanks for reporting this issue. It seems that the difference between both paths is the file they are referencing: `transformer_csv.py` vs `transformer.py`. I've never seen this issue before. Were you able to work around it?

**Comment by jairaws** [comment]
Figured out the problem. The path is too long, and it hits the `MAX_PATH` limit in Windows. See this `moto` [PR](https://github.com/getmoto/moto/issues/7536) for reference.

You can enable long paths by updating the registry. Here the [instructions](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=powershell) to do so.
